import type { Metadata } from "next";
import { Nunito, Kanit } from "next/font/google";
import "./globals.css";
import Wrapper from "@/app/[locale]/_components/Wrapper";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin"],
  weight: ["400"], 
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`${kanit.variable} ${nunito.variable} antialiased bg-[#191D1D] text-white`}
        >
          <Wrapper>
            <Header />
            {children}
            <Footer />
          </Wrapper>
        </body>
    </html>
  );
}
